adjacency: adj_io.o adj_path.o adjacency.o adjacency.h
	gcc -g -Wall -ansi -pedantic adj_io.o adj_path.o adjacency.o adjacency.h -o adjacency
adj_io.o: adj_io.c
	gcc -c -Wall -ansi -pedantic adj_io.c -o adj_io.o
adj_path.o: adj_path.c
	gcc -c -Wall -ansi -pedantic adj_path.c -o adj_path.o
adjacency.o: adjacency.c
	gcc -c -Wall -ansi -pedantic adjacency.c -o adjacency.o