sequence: f_sequence.o sequence.o
	gcc -g -Wall -ansi -pedantic f_sequence.o sequence.o -o sequence
f_sequence.o: f_sequence.c
	gcc -c -Wall -ansi -pedantic f_sequence.c -o f_sequence.o
sequence.o: sequence.c
	gcc -c -Wall -ansi -pedantic sequence.c -o sequence.o